spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  application:
    name: auction
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#        jdbc:
#          batch_size: 20          # 한 번에 처리할 배치 크기
#        order_inserts: true        # INSERT 쿼리 정렬
#        order_updates: true
    #        default_batch_fetch_size: 100

    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8080


